CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    version INT NOT NULL DEFAULT 0
);

INSERT INTO roles (name) VALUES
('ADMIN'),
('PATIENT'),
('CAREGIVER'),
('HEALTHCARE_PROVIDER');